rectangleSquare: main.o rectangleSquare.o
	g++ main.o rectangleSquare.o

main.o: main.cpp
	g++ -c main.cpp

rectangleSquare.o: rectangleSquare.cpp
	g++ -c rectangleSquare.cpp

clean:
	rm rectangleSquare.o
	rm main.o
